// ============================================================
// 太阳系天体数据（中英双语）
// 每个文本字段均提供中文（默认）与英文（后缀 _en）两个版本。
//  kind      星球类别: star(恒星) / rock(岩石) / gas(气态) / ice(冰巨星) / dwarf(矮行星) / belt(星带)
//  gravity   以地球为基准 1 的表面重力
//  orbitRadius / radius / orbitPeriod / rotationSpeed / tilt 为 3D 渲染参数(视觉比例)
// ============================================================

export const SUN = {
  id: 'sun',
  name: '太阳',
  en: 'Sun',
  kind: 'star',
  type: '恒星（G 型主序星）',
  type_en: 'Star (G-type main-sequence)',
  desc: '太阳系的中心恒星，占据了太阳系总质量的 99.86%，通过核心的氢核聚变持续释放光和热，是地球一切生命的能量之源。',
  desc_en: 'The star at the center of the Solar System, holding 99.86% of its total mass and releasing light and heat through hydrogen fusion in its core — the energy source for all life on Earth.',
  age: '约 46 亿年',
  age_en: '~4.6 billion years',
  diameter: '1,392,700 km',
  satellites: 8,
  satellitesNote: '颗行星（八大行星）',
  satellitesNote_en: 'planets (the eight planets)',
  composition: ['氢 (H) ~73%', '氦 (He) ~25%', '氧 / 碳 / 铁等 ~2%'],
  composition_en: ['Hydrogen (H) ~73%', 'Helium (He) ~25%', 'Oxygen / Carbon / Iron ~2%'],
  rotationPeriod: '约 25.4 天（赤道）',
  rotationPeriod_en: '~25.4 days (at equator)',
  revolutionPeriod: '约 2.3 亿年（绕银河系中心）',
  revolutionPeriod_en: '~230 million years (around the galactic center)',
  gravity: 27.9,
  color: '#ffb52e',
  texture: 'assets/textures/sun.jpg',
  radius: 4.5,
  rotationSpeed: 0.04,
};

export const PLANETS = [
  {
    id: 'mercury',
    name: '水星',
    en: 'Mercury',
    kind: 'rock',
    type: '岩石（类地行星）',
    type_en: 'Rocky (terrestrial planet)',
    desc: '离太阳最近、也是太阳系中最小的行星，表面布满陨石坑，几乎没有大气层，昼夜温差可高达约 600°C。',
    desc_en: "The closest planet to the Sun and the smallest, its cratered surface has almost no atmosphere, with day–night temperature swings of about 600 °C.",
    age: '约 45 亿年',
    age_en: '~4.5 billion years',
    diameter: '4,879 km',
    satellites: 0,
    composition: ['铁 (Fe)', '氧 (O)', '硅 (Si)', '镁 (Mg)'],
    composition_en: ['Iron (Fe)', 'Oxygen (O)', 'Silicon (Si)', 'Magnesium (Mg)'],
    rotationPeriod: '58.6 天',
    rotationPeriod_en: '58.6 days',
    revolutionPeriod: '88 天',
    revolutionPeriod_en: '88 days',
    gravity: 0.38,
    color: '#9c8e82',
    texture: 'assets/textures/mercury.jpg',
    radius: 0.35,
    orbitRadius: 9,
    orbitPeriod: 18,
    rotationSpeed: 0.02,
    tilt: 0.03,
  },
  {
    id: 'venus',
    name: '金星',
    en: 'Venus',
    kind: 'rock',
    type: '岩石（类地行星）',
    type_en: 'Rocky (terrestrial planet)',
    desc: '太阳系中最热的行星，浓厚的二氧化碳大气造成强烈的温室效应，表面温度高达约 460°C。',
    desc_en: 'The hottest planet in the Solar System, with a thick carbon-dioxide atmosphere causing a runaway greenhouse effect and surface temperatures of about 460 °C.',
    age: '约 45 亿年',
    age_en: '~4.5 billion years',
    diameter: '12,104 km',
    satellites: 0,
    composition: ['二氧化碳 (CO₂) 大气', '硅酸盐岩石', '铁核 (Fe)'],
    composition_en: ['Carbon dioxide (CO₂) atmosphere', 'Silicate rock', 'Iron core (Fe)'],
    rotationPeriod: '243 天（逆向）',
    rotationPeriod_en: '243 days (retrograde)',
    revolutionPeriod: '224.7 天',
    revolutionPeriod_en: '224.7 days',
    gravity: 0.91,
    color: '#e6c88a',
    texture: 'assets/textures/venus_atmosphere.jpg',
    radius: 0.62,
    orbitRadius: 12.5,
    orbitPeriod: 26,
    rotationSpeed: -0.015,
    tilt: 0.05,
  },
  {
    id: 'earth',
    name: '地球',
    en: 'Earth',
    kind: 'rock',
    type: '岩石（类地行星）',
    type_en: 'Rocky (terrestrial planet)',
    desc: '目前已知唯一存在生命的行星，表面约 71% 被液态水覆盖，拥有适宜生命繁衍的大气与磁场。',
    desc_en: 'The only known planet with life, about 71% of its surface is covered by liquid water, with an atmosphere and magnetic field that support life.',
    age: '约 45.4 亿年',
    age_en: '~4.54 billion years',
    diameter: '12,742 km',
    satellites: 1,
    composition: ['铁 (Fe)', '氧 (O)', '硅 (Si)', '镁 (Mg)', '氮 (N)'],
    composition_en: ['Iron (Fe)', 'Oxygen (O)', 'Silicon (Si)', 'Magnesium (Mg)', 'Nitrogen (N)'],
    rotationPeriod: '23.9 小时',
    rotationPeriod_en: '23.9 hours',
    revolutionPeriod: '365.25 天',
    revolutionPeriod_en: '365.25 days',
    gravity: 1.0,
    color: '#4f8fd9',
    texture: 'assets/textures/earth_daymap.jpg',
    radius: 0.66,
    orbitRadius: 16,
    orbitPeriod: 34,
    rotationSpeed: 0.1,
    tilt: 0.41,
  },
  {
    id: 'mars',
    name: '火星',
    en: 'Mars',
    kind: 'rock',
    type: '岩石（类地行星）',
    type_en: 'Rocky (terrestrial planet)',
    desc: '因表面富含氧化铁而呈红色的岩石行星，拥有太阳系最高的火山——奥林帕斯山和壮观的峡谷地貌。',
    desc_en: "A red rocky planet rich in iron oxide, home to the Solar System's tallest volcano, Olympus Mons, and spectacular canyon systems.",
    age: '约 45 亿年',
    age_en: '~4.5 billion years',
    diameter: '6,779 km',
    satellites: 2,
    composition: ['铁氧化物 (Fe₂O₃)', '硅酸盐岩石', '二氧化碳 (CO₂) 大气'],
    composition_en: ['Iron oxide (Fe₂O₃)', 'Silicate rock', 'Carbon dioxide (CO₂) atmosphere'],
    rotationPeriod: '24.6 小时',
    rotationPeriod_en: '24.6 hours',
    revolutionPeriod: '687 天',
    revolutionPeriod_en: '687 days',
    gravity: 0.38,
    color: '#d1683f',
    texture: 'assets/textures/mars.jpg',
    radius: 0.48,
    orbitRadius: 19.5,
    orbitPeriod: 44,
    rotationSpeed: 0.09,
    tilt: 0.44,
  },
  {
    id: 'jupiter',
    name: '木星',
    en: 'Jupiter',
    kind: 'gas',
    type: '气态巨行星',
    type_en: 'Gas giant',
    desc: '太阳系中最大的行星，质量是其他所有行星总和的 2.5 倍，拥有著名的“大红斑”巨型风暴。',
    desc_en: 'The largest planet in the Solar System, 2.5 times the mass of all other planets combined, famous for its Great Red Spot storm.',
    age: '约 46 亿年',
    age_en: '~4.6 billion years',
    diameter: '139,820 km',
    satellites: 95,
    composition: ['氢 (H)', '氦 (He)', '甲烷 / 氨 / 水'],
    composition_en: ['Hydrogen (H)', 'Helium (He)', 'Methane / Ammonia / Water'],
    rotationPeriod: '9.9 小时',
    rotationPeriod_en: '9.9 hours',
    revolutionPeriod: '11.86 年',
    revolutionPeriod_en: '11.86 years',
    gravity: 2.53,
    color: '#c9a06a',
    texture: 'assets/textures/jupiter.jpg',
    radius: 2.4,
    orbitRadius: 31,
    orbitPeriod: 70,
    rotationSpeed: 0.22,
    tilt: 0.05,
  },
  {
    id: 'saturn',
    name: '土星',
    en: 'Saturn',
    kind: 'gas',
    type: '气态巨行星',
    type_en: 'Gas giant',
    desc: '以壮丽光环著称的气态巨行星，其平均密度甚至比水还低，拥有太阳系最多的已知卫星。',
    desc_en: 'A gas giant renowned for its magnificent rings, with an average density even lower than water and the most known moons of any planet.',
    age: '约 46 亿年',
    age_en: '~4.6 billion years',
    diameter: '116,460 km',
    satellites: 146,
    composition: ['氢 (H)', '氦 (He)', '甲烷 / 氨'],
    composition_en: ['Hydrogen (H)', 'Helium (He)', 'Methane / Ammonia'],
    rotationPeriod: '10.7 小时',
    rotationPeriod_en: '10.7 hours',
    revolutionPeriod: '29.4 年',
    revolutionPeriod_en: '29.4 years',
    gravity: 1.07,
    color: '#e0c58f',
    texture: 'assets/textures/saturn.jpg',
    radius: 2.0,
    orbitRadius: 38,
    orbitPeriod: 95,
    rotationSpeed: 0.2,
    tilt: 0.47,
    ring: true,
  },
  {
    id: 'uranus',
    name: '天王星',
    en: 'Uranus',
    kind: 'ice',
    type: '冰巨星（气态）',
    type_en: 'Ice giant',
    desc: '自转轴几乎“躺倒”公转的冰巨星，因大气中的甲烷而呈现淡蓝绿色。',
    desc_en: 'An ice giant that orbits almost tipped over on its side, appearing pale blue-green from methane in its atmosphere.',
    age: '约 46 亿年',
    age_en: '~4.6 billion years',
    diameter: '50,724 km',
    satellites: 28,
    composition: ['氢 (H)', '氦 (He)', '甲烷 (CH₄)', '水冰'],
    composition_en: ['Hydrogen (H)', 'Helium (He)', 'Methane (CH₄)', 'Water ice'],
    rotationPeriod: '17.2 小时（逆向）',
    rotationPeriod_en: '17.2 hours (retrograde)',
    revolutionPeriod: '84 年',
    revolutionPeriod_en: '84 years',
    gravity: 0.89,
    color: '#9fe0e0',
    texture: 'assets/textures/uranus.jpg',
    radius: 1.3,
    orbitRadius: 46,
    orbitPeriod: 125,
    rotationSpeed: -0.16,
    tilt: 1.71,
  },
  {
    id: 'neptune',
    name: '海王星',
    en: 'Neptune',
    kind: 'ice',
    type: '冰巨星（气态）',
    type_en: 'Ice giant',
    desc: '太阳系中离太阳最远的行星，呈现深邃的蓝色，拥有太阳系中最猛烈的风暴与最快的风速。',
    desc_en: 'The farthest planet from the Sun, deep blue in color, with the strongest storms and fastest winds in the Solar System.',
    age: '约 46 亿年',
    age_en: '~4.6 billion years',
    diameter: '49,244 km',
    satellites: 16,
    composition: ['氢 (H)', '氦 (He)', '甲烷 (CH₄)'],
    composition_en: ['Hydrogen (H)', 'Helium (He)', 'Methane (CH₄)'],
    rotationPeriod: '16.1 小时',
    rotationPeriod_en: '16.1 hours',
    revolutionPeriod: '164.8 年',
    revolutionPeriod_en: '164.8 years',
    gravity: 1.14,
    color: '#3f6fd9',
    texture: 'assets/textures/neptune.jpg',
    radius: 1.25,
    orbitRadius: 53,
    orbitPeriod: 155,
    rotationSpeed: 0.15,
    tilt: 0.49,
  },
];

export const PLUTO = {
  id: 'pluto',
  name: '冥王星',
  en: 'Pluto',
  kind: 'dwarf',
  type: '岩石 + 冰（矮行星）',
  type_en: 'Rocky + icy (dwarf planet)',
  desc: '曾被列为太阳系第九大行星，2006 年被重新分类为矮行星，是柯伊伯带中最著名的天体。',
  desc_en: 'Once the ninth planet, reclassified as a dwarf planet in 2006; the best-known object in the Kuiper Belt.',
  age: '约 45 亿年',
  age_en: '~4.5 billion years',
  diameter: '2,377 km',
  satellites: 5,
  composition: ['氮冰 (N₂)', '甲烷冰 (CH₄)', '一氧化碳冰 (CO)', '岩石'],
  composition_en: ['Nitrogen ice (N₂)', 'Methane ice (CH₄)', 'Carbon monoxide ice (CO)', 'Rock'],
  rotationPeriod: '6.4 天',
  rotationPeriod_en: '6.4 days',
  revolutionPeriod: '248 年',
  revolutionPeriod_en: '248 years',
  gravity: 0.06,
  color: '#c9b79b',
  texture: null, // 使用程序化生成纹理
  radius: 0.22,
  orbitRadius: 63,
  orbitPeriod: 185,
  rotationSpeed: 0.02,
  tilt: 2.16,
};

export const DWARF_PLANETS = [
  {
    id: 'ceres',
    name: '谷神星',
    en: 'Ceres',
    kind: 'dwarf',
    type: '岩石 + 冰（矮行星）',
    type_en: 'Rocky + icy (dwarf planet)',
    desc: '小行星带中最大的天体，也是带内唯一的矮行星，早期曾被视作一颗行星。',
    desc_en: 'The largest object in the asteroid belt and its only dwarf planet; it was once considered a planet.',
    age: '约 45 亿年',
    age_en: '~4.5 billion years',
    diameter: '940 km',
    satellites: 0,
    composition: ['水冰', '硅酸盐岩石'],
    composition_en: ['Water ice', 'Silicate rock'],
    rotationPeriod: '9.1 小时',
    rotationPeriod_en: '9.1 hours',
    revolutionPeriod: '4.6 年',
    revolutionPeriod_en: '4.6 years',
    gravity: 0.03,
    color: '#9a8f82',
    texture: null,
    radius: 0.16,
    orbitRadius: 25.5,
    orbitPeriod: 55,
    rotationSpeed: 0.05,
    tilt: 0.07,
  },
  {
    id: 'haumea',
    name: '妊神星',
    en: 'Haumea',
    kind: 'dwarf',
    type: '岩石 + 冰（矮行星）',
    type_en: 'Rocky + icy (dwarf planet)',
    desc: '因极快速自转而呈明显椭球状的矮行星，并拥有独特的环系统。',
    desc_en: 'A dwarf planet distinctly ellipsoidal from its extremely fast spin, and possessing a ring system.',
    age: '约 45 亿年',
    age_en: '~4.5 billion years',
    diameter: '~1,632 km',
    satellites: 2,
    composition: ['水冰', '岩石'],
    composition_en: ['Water ice', 'Rock'],
    rotationPeriod: '3.9 小时',
    rotationPeriod_en: '3.9 hours',
    revolutionPeriod: '283 年',
    revolutionPeriod_en: '283 years',
    gravity: 0.04,
    color: '#d8d8e0',
    texture: null,
    radius: 0.2,
    orbitRadius: 59,
    orbitPeriod: 200,
    rotationSpeed: 0.12,
    tilt: 0.3,
  },
  {
    id: 'makemake',
    name: '鸟神星',
    en: 'Makemake',
    kind: 'dwarf',
    type: '岩石 + 冰（矮行星）',
    type_en: 'Rocky + icy (dwarf planet)',
    desc: '表面覆盖甲烷冰、呈现淡红色调的柯伊伯带矮行星。',
    desc_en: 'A Kuiper Belt dwarf planet covered in methane ice with a reddish tint.',
    age: '约 45 亿年',
    age_en: '~4.5 billion years',
    diameter: '1,430 km',
    satellites: 1,
    composition: ['甲烷冰 (CH₄)', '乙烷冰', '岩石'],
    composition_en: ['Methane ice (CH₄)', 'Ethane ice', 'Rock'],
    rotationPeriod: '22.5 小时',
    rotationPeriod_en: '22.5 hours',
    revolutionPeriod: '309 年',
    revolutionPeriod_en: '309 years',
    gravity: 0.04,
    color: '#c9a08a',
    texture: null,
    radius: 0.19,
    orbitRadius: 67,
    orbitPeriod: 215,
    rotationSpeed: 0.02,
    tilt: 0.1,
  },
  {
    id: 'eris',
    name: '阋神星',
    en: 'Eris',
    kind: 'dwarf',
    type: '岩石 + 冰（矮行星）',
    type_en: 'Rocky + icy (dwarf planet)',
    desc: '质量比冥王星略大的矮行星，位于海王星之外的弥散盘，是已知最远的矮行星之一。',
    desc_en: 'A dwarf planet slightly more massive than Pluto, located in the scattered disc beyond Neptune — one of the most distant known dwarf planets.',
    age: '约 45 亿年',
    age_en: '~4.5 billion years',
    diameter: '2,326 km',
    satellites: 1,
    composition: ['氮冰 (N₂)', '甲烷冰 (CH₄)', '岩石'],
    composition_en: ['Nitrogen ice (N₂)', 'Methane ice (CH₄)', 'Rock'],
    rotationPeriod: '25.9 小时',
    rotationPeriod_en: '25.9 hours',
    revolutionPeriod: '557 年',
    revolutionPeriod_en: '557 years',
    gravity: 0.08,
    color: '#e8e8e0',
    texture: null,
    radius: 0.21,
    orbitRadius: 77,
    orbitPeriod: 240,
    rotationSpeed: 0.02,
    tilt: 0.2,
  },
];

export const BELTS = [
  {
    id: 'asteroidBelt',
    name: '小行星带',
    en: 'Asteroid Belt',
    kind: 'belt',
    color: '#c2a98a',
    location: '火星与木星之间（约 2.2–3.2 天文单位）',
    location_en: 'Between Mars and Jupiter (~2.2–3.2 AU)',
    intro: '小行星带是位于火星与木星轨道之间的一片小天体密集区，由太阳系形成初期的岩石质残留物组成，是研究太阳系早期历史的重要“化石”宝库。',
    intro_en: 'The asteroid belt is a dense region of small bodies between the orbits of Mars and Jupiter, made of rocky debris left over from the Solar System\'s formation — a "fossil" record of its early history.',
    introItems: [
      {
        title: '位置与范围',
        text: '介于火星与木星轨道之间，主要分布在约 2.2–3.2 天文单位（约 3.3 亿–4.8 亿公里）的环带区域。',
      },
      {
        title: '形成与起源',
        text: '是太阳系形成初期的残留物质，因木星强大引力的扰动而未能聚合成一颗大行星，最终以无数小天体的形式留存至今。',
      },
      {
        title: '天体数量',
        text: '带内已知小行星超过 100 万颗（直径大于 1 公里），若计入更小天体则数以千万计；但总质量仅约为月球质量的 3%–4%。',
      },
      {
        title: '主要成员',
        text: '谷神星（Ceres，矮行星）、灶神星（Vesta）、智神星（Pallas）、健神星（Hygiea）等。',
      },
    ],
    introItems_en: [
      {
        title: 'Location & Extent',
        text: 'Between the orbits of Mars and Jupiter, mostly 2.2–3.2 AU (about 330–480 million km) from the Sun.',
      },
      {
        title: 'Formation & Origin',
        text: "Debris from the Solar System's formation; Jupiter's strong gravity prevented these bodies from coalescing into a planet.",
      },
      {
        title: 'Number of Objects',
        text: "Over 1 million known asteroids (larger than 1 km), with millions more smaller bodies; yet the total mass is only 3–4% of the Moon's mass.",
      },
      {
        title: 'Major Members',
        text: 'Ceres (a dwarf planet), Vesta, Pallas, Hygiea, and others.',
      },
    ],
    count: '超过 100 万颗（直径 > 1 km）',
    count_en: 'Over 1 million (diameter > 1 km)',
    mainBodies: [
      { name: '谷神星 Ceres', diameter: '940 km', type: '矮行星（岩石 + 冰）', desc: '带内最大天体，约占带内总质量的三分之一，早期曾被视作一颗行星。' },
      { name: '灶神星 Vesta', diameter: '525 km', type: '岩石小行星', desc: '带内第二大小行星，也是带内最亮的小行星，表面有巨大的撞击坑。' },
      { name: '智神星 Pallas', diameter: '512 km', type: '岩石小行星', desc: '轨道倾角极大（约 34°），是带内第三大的小行星。' },
      { name: '健神星 Hygiea', diameter: '434 km', type: '岩石小行星', desc: '外形接近球形，被认为是可能符合矮行星标准的天体。' },
    ],
    mainBodies_en: [
      { name: 'Ceres', diameter: '940 km', type: 'Dwarf planet (rocky + icy)', desc: 'The largest object in the belt, holding about one-third of its total mass; once considered a planet.' },
      { name: 'Vesta', diameter: '525 km', type: 'Rocky asteroid', desc: 'The second-largest and brightest asteroid in the belt, with giant impact craters.' },
      { name: 'Pallas', diameter: '512 km', type: 'Rocky asteroid', desc: 'The third-largest asteroid, with an unusually high orbital inclination (~34°).' },
      { name: 'Hygiea', diameter: '434 km', type: 'Rocky asteroid', desc: 'Nearly spherical, and considered a candidate for dwarf-planet status.' },
    ],
    // 渲染参数
    innerRadius: 23,
    outerRadius: 27,
    particleCount: 2600,
    thickness: 1.4,
    rotationSpeed: 0.01,
  },
  {
    id: 'kuiperBelt',
    name: '柯伊伯带',
    en: 'Kuiper Belt',
    kind: 'belt',
    color: '#8fb4d9',
    location: '海王星轨道之外（约 30–55 天文单位）',
    location_en: 'Beyond Neptune (~30–55 AU)',
    intro: '柯伊伯带是海王星轨道之外的一片广阔冰质天体环带，由太阳系形成初期的冰质残留物构成，也是许多短周期彗星（如哈雷彗星）的故乡。',
    intro_en: 'The Kuiper Belt is a vast ring of icy bodies beyond Neptune, made of icy debris from the Solar System\'s formation and the birthplace of many short-period comets such as Halley\'s Comet.',
    introItems: [
      {
        title: '位置与范围',
        text: '位于海王星轨道之外，从约 30 天文单位延伸到约 55 天文单位（约 45 亿–82 亿公里），是一片广阔的冰质环带。',
      },
      {
        title: '形成与起源',
        text: '由太阳系形成初期的冰质残余物构成，因距太阳遥远、物质密度过低而未能聚合成行星，是短周期彗星的主要发源地。',
      },
      {
        title: '天体数量',
        text: '已知柯伊伯带天体超过 10 万颗（直径大于 100 公里），若计入更小天体则总数可能以亿计，其中包含多颗矮行星。',
      },
      {
        title: '主要成员',
        text: '冥王星（Pluto）、阋神星（Eris）、鸟神星（Makemake）、妊神星（Haumea）等矮行星。',
      },
    ],
    introItems_en: [
      {
        title: 'Location & Extent',
        text: "Beyond Neptune's orbit, stretching from about 30 to 55 AU (4.5–8.2 billion km) from the Sun.",
      },
      {
        title: 'Formation & Origin',
        text: "Icy debris from the Solar System's formation; too far and too sparse to form a planet, and the main source of short-period comets.",
      },
      {
        title: 'Number of Objects',
        text: 'Over 100,000 known objects (larger than 100 km), possibly hundreds of millions in total, including several dwarf planets.',
      },
      {
        title: 'Major Members',
        text: 'Pluto, Eris, Makemake, Haumea, and other dwarf planets.',
      },
    ],
    count: '超过 10 万颗（直径 > 100 km）',
    count_en: 'Over 100,000 (diameter > 100 km)',
    mainBodies: [
      { name: '冥王星 Pluto', diameter: '2,377 km', type: '矮行星（岩石 + 冰）', desc: '带内最著名的天体，拥有 5 颗卫星，与冥卫一（卡戎）近似构成双星系统。' },
      { name: '阋神星 Eris', diameter: '2,326 km', type: '矮行星（冰）', desc: '质量略大于冥王星，它的发现直接促成了“矮行星”这一分类的建立。' },
      { name: '鸟神星 Makemake', diameter: '1,430 km', type: '矮行星（冰）', desc: '表面覆盖甲烷冰，呈现淡红色调。' },
      { name: '妊神星 Haumea', diameter: '1,632 km', type: '矮行星（冰 + 岩石）', desc: '因快速自转呈明显椭球状，且拥有独特的环系统。' },
    ],
    mainBodies_en: [
      { name: 'Pluto', diameter: '2,377 km', type: 'Dwarf planet (rocky + icy)', desc: 'The best-known Kuiper Belt object, with 5 moons; Charon is so large the pair is almost a double system.' },
      { name: 'Eris', diameter: '2,326 km', type: 'Dwarf planet (icy)', desc: 'Slightly more massive than Pluto; its discovery led to the dwarf-planet classification.' },
      { name: 'Makemake', diameter: '1,430 km', type: 'Dwarf planet (icy)', desc: 'Covered in methane ice with a reddish tint.' },
      { name: 'Haumea', diameter: '1,632 km', type: 'Dwarf planet (icy + rocky)', desc: 'Distinctly ellipsoidal from its rapid spin, and possesses a ring system.' },
    ],
    // 渲染参数
    innerRadius: 58,
    outerRadius: 74,
    particleCount: 3800,
    thickness: 2.2,
    rotationSpeed: 0.006,
  },
];

// ============================================================
// 小测验题目（基于上方太阳系知识，4 选 1；中英双语）
// answer 为正确选项的下标（从 0 开始，两种语言共用同一答案下标）
// ============================================================
export const QUIZ = [
  {
    question: '太阳系中体积最大的行星是？',
    question_en: 'Which is the largest planet in the Solar System?',
    options: ['土星', '木星', '天王星', '海王星'],
    options_en: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'],
    answer: 1,
    explain: '木星直径约 139,820 km，是太阳系中最大的行星。',
    explain_en: 'Jupiter is about 139,820 km in diameter, the largest planet in the Solar System.',
  },
  {
    question: '小行星带主要位于哪两颗行星的轨道之间？',
    question_en: 'The asteroid belt lies mainly between which two planets?',
    options: ['地球与火星', '火星与木星', '木星与土星', '天王星与海王星'],
    options_en: ['Earth and Mars', 'Mars and Jupiter', 'Jupiter and Saturn', 'Uranus and Neptune'],
    answer: 1,
    explain: '小行星带位于火星与木星之间，约 2.2–3.2 天文单位处。',
    explain_en: 'The asteroid belt lies between Mars and Jupiter, around 2.2–3.2 AU from the Sun.',
  },
  {
    question: '曾被列为太阳系第九大行星、后被重新分类为矮行星的是？',
    question_en: 'Which body was once the ninth planet and was reclassified as a dwarf planet?',
    options: ['谷神星', '阋神星', '冥王星', '海王星'],
    options_en: ['Ceres', 'Eris', 'Pluto', 'Neptune'],
    answer: 2,
    explain: '冥王星曾被视为第九大行星，2006 年被重新分类为矮行星。',
    explain_en: 'Pluto was considered the ninth planet until it was reclassified as a dwarf planet in 2006.',
  },
  {
    question: '太阳主要由哪两种元素构成？',
    question_en: 'What two elements is the Sun mainly made of?',
    options: ['氧和铁', '碳和硅', '氮和氧', '氢和氦'],
    options_en: ['Oxygen and iron', 'Carbon and silicon', 'Nitrogen and oxygen', 'Hydrogen and helium'],
    answer: 3,
    explain: '太阳约 73% 是氢、25% 是氦，通过核心的氢核聚变释放能量。',
    explain_en: 'The Sun is about 73% hydrogen and 25% helium, powered by hydrogen fusion.',
  },
  {
    question: '目前已知卫星数量最多的行星是？',
    question_en: 'Which planet has the most known moons?',
    options: ['木星', '海王星', '土星', '天王星'],
    options_en: ['Jupiter', 'Neptune', 'Saturn', 'Uranus'],
    answer: 2,
    explain: '土星已知卫星约 146 颗，是已知卫星数量最多的行星。',
    explain_en: 'Saturn has about 146 known moons, the most of any planet.',
  },
  {
    question: '离太阳最近的行星是？',
    question_en: 'Which planet is closest to the Sun?',
    options: ['金星', '地球', '水星', '火星'],
    options_en: ['Venus', 'Earth', 'Mercury', 'Mars'],
    answer: 2,
    explain: '水星是离太阳最近、也是最小的行星，表面布满陨石坑。',
    explain_en: 'Mercury is the closest planet to the Sun and also the smallest.',
  },
  {
    question: '太阳系中表面温度最高的行星是？',
    question_en: 'Which planet has the hottest surface?',
    options: ['水星', '火星', '金星', '木星'],
    options_en: ['Mercury', 'Mars', 'Venus', 'Jupiter'],
    answer: 2,
    explain: '金星因浓密二氧化碳大气的强烈温室效应，表面温度高达约 460°C。',
    explain_en: "Venus's thick CO₂ atmosphere creates a runaway greenhouse effect, reaching about 460 °C.",
  },
  {
    question: '被称为“红色星球”、表面富含氧化铁的是？',
    question_en: 'Which planet is known as the "Red Planet" for its iron-oxide surface?',
    options: ['金星', '火星', '木星', '水星'],
    options_en: ['Venus', 'Mars', 'Jupiter', 'Mercury'],
    answer: 1,
    explain: '火星表面富含氧化铁（Fe₂O₃），因此呈现红色。',
    explain_en: 'Mars is rich in iron oxide (Fe₂O₃), giving it its red color.',
  },
  {
    question: '目前已知唯一存在生命的行星是？',
    question_en: 'Which planet is the only one known to harbor life?',
    options: ['火星', '金星', '地球', '木星'],
    options_en: ['Mars', 'Venus', 'Earth', 'Jupiter'],
    answer: 2,
    explain: '地球表面约 71% 被液态水覆盖，是已知唯一存在生命的行星。',
    explain_en: "About 71% of Earth's surface is liquid water; it is the only known life-bearing planet.",
  },
  {
    question: '太阳系中拥有最高火山（奥林帕斯山）的行星是？',
    question_en: 'Which planet has the tallest volcano (Olympus Mons)?',
    options: ['地球', '金星', '火星', '水星'],
    options_en: ['Earth', 'Venus', 'Mars', 'Mercury'],
    answer: 2,
    explain: '火星拥有太阳系最高的火山——奥林帕斯山。',
    explain_en: 'Mars hosts Olympus Mons, the tallest volcano in the Solar System.',
  },
  {
    question: '柯伊伯带位于哪里？',
    question_en: 'Where is the Kuiper Belt located?',
    options: ['火星与木星之间', '地球轨道附近', '海王星轨道之外', '水星与金星之间'],
    options_en: ['Between Mars and Jupiter', "Near Earth's orbit", "Beyond Neptune's orbit", 'Between Mercury and Venus'],
    answer: 2,
    explain: '柯伊伯带位于海王星轨道之外，约 30–55 天文单位，是冰质天体的家园。',
    explain_en: 'The Kuiper Belt lies beyond Neptune, about 30–55 AU from the Sun.',
  },
  {
    question: '土星最著名的特征是？',
    question_en: 'What is Saturn best known for?',
    options: ['大红斑', '壮丽的光环', '最高的火山', '逆向自转'],
    options_en: ['The Great Red Spot', 'Its magnificent rings', 'The tallest volcano', 'Retrograde rotation'],
    answer: 1,
    explain: '土星以壮丽的光环著称，其平均密度甚至比水还低。',
    explain_en: 'Saturn is famous for its magnificent rings, and its density is even lower than water.',
  },
  {
    question: '太阳系中自转最快的行星是？',
    question_en: 'Which planet spins the fastest?',
    options: ['地球', '木星', '火星', '水星'],
    options_en: ['Earth', 'Jupiter', 'Mars', 'Mercury'],
    answer: 1,
    explain: '木星自转周期仅约 9.9 小时，是自转最快的行星。',
    explain_en: "Jupiter's rotation period is only about 9.9 hours — the fastest of the planets.",
  },
  {
    question: '天王星呈现淡蓝绿色的主要原因是大气中含有？',
    question_en: 'What makes Uranus appear blue-green?',
    options: ['二氧化碳', '甲烷', '氧气', '氮气'],
    options_en: ['Carbon dioxide', 'Methane', 'Oxygen', 'Nitrogen'],
    answer: 1,
    explain: '天王星大气中的甲烷吸收红光，使其呈现淡蓝绿色。',
    explain_en: "Methane in Uranus's atmosphere absorbs red light, giving it a blue-green tint.",
  },
  {
    question: '以地球重力为 1，木星的表面重力约为？',
    question_en: "With Earth's gravity as 1, Jupiter's surface gravity is about?",
    options: ['0.38 倍', '0.91 倍', '1.14 倍', '2.53 倍'],
    options_en: ['0.38', '0.91', '1.14', '2.53'],
    answer: 3,
    explain: '木星表面重力约为地球的 2.53 倍。',
    explain_en: "Jupiter's surface gravity is about 2.53 times Earth's.",
  },
  {
    question: '地球的天然卫星数量是？',
    question_en: 'How many natural satellites does Earth have?',
    options: ['0 颗', '1 颗', '2 颗', '5 颗'],
    options_en: ['0', '1', '2', '5'],
    answer: 1,
    explain: '地球有 1 颗天然卫星——月球。',
    explain_en: 'Earth has one natural satellite — the Moon.',
  },
  {
    question: '太阳的年龄约为？',
    question_en: 'How old is the Sun?',
    options: ['约 1 亿年', '约 10 亿年', '约 46 亿年', '约 460 亿年'],
    options_en: ['~100 million years', '~1 billion years', '~4.6 billion years', '~46 billion years'],
    answer: 2,
    explain: '太阳的年龄约为 46 亿年。',
    explain_en: 'The Sun is about 4.6 billion years old.',
  },
  {
    question: '以地球重力为 1，水星的表面重力约为？',
    question_en: "With Earth's gravity as 1, Mercury's surface gravity is about?",
    options: ['0.38 倍', '0.91 倍', '1.07 倍', '2.53 倍'],
    options_en: ['0.38', '0.91', '1.07', '2.53'],
    answer: 0,
    explain: '水星表面重力约为地球的 0.38 倍。',
    explain_en: "Mercury's surface gravity is about 0.38 times Earth's.",
  },
  {
    question: '小行星带中最大的天体是？',
    question_en: 'What is the largest object in the asteroid belt?',
    options: ['灶神星', '谷神星', '智神星', '健神星'],
    options_en: ['Vesta', 'Ceres', 'Pallas', 'Hygiea'],
    answer: 1,
    explain: '谷神星直径约 940 km，是小行星带中最大的天体，也是带内唯一的矮行星。',
    explain_en: 'Ceres is about 940 km in diameter, the largest object in the asteroid belt and its only dwarf planet.',
  },
  {
    question: '太阳系中已知最远的矮行星是？',
    question_en: 'Which is the most distant known dwarf planet?',
    options: ['谷神星', '冥王星', '阋神星', '鸟神星'],
    options_en: ['Ceres', 'Pluto', 'Eris', 'Makemake'],
    answer: 2,
    explain: '阋神星（Eris）位于海王星之外的弥散盘，是目前已知距离太阳最远的矮行星，质量也略大于冥王星。',
    explain_en: 'Eris lies in the scattered disc beyond Neptune and is the most distant known dwarf planet, slightly more massive than Pluto.',
  },
  {
    question: '太阳系最遥远、被认为是长周期彗星发源地的区域是？',
    question_en: 'What is the most distant region of the Solar System, thought to be the source of long-period comets?',
    options: ['小行星带', '柯伊伯带', '奥尔特云', '弥散盘'],
    options_en: ['Asteroid Belt', 'Kuiper Belt', 'Oort Cloud', 'Scattered Disc'],
    answer: 2,
    explain: '奥尔特云是包裹太阳系的巨大球形云团，距太阳约 2,000–100,000 天文单位，是太阳系最遥远的地方，也是长周期彗星的发源地。',
    explain_en: 'The Oort Cloud is a vast spherical shell around the Solar System, roughly 2,000–100,000 AU from the Sun — the most distant part of the Solar System and the source of long-period comets.',
  },
  {
    question: '土星大约有多少颗已知卫星？',
    question_en: 'About how many known moons does Saturn have?',
    options: ['约 95 颗', '约 146 颗', '约 28 颗', '约 16 颗'],
    options_en: ['About 95', 'About 146', 'About 28', 'About 16'],
    answer: 1,
    explain: '土星已知卫星约 146 颗，是太阳系中已知卫星数量最多的行星。',
    explain_en: 'Saturn has about 146 known moons, the most of any planet in the Solar System.',
  },
  {
    question: '木星的体积大约能容纳多少个地球？',
    question_en: 'About how many Earths could fit inside Jupiter?',
    options: ['约 10 个', '约 100 个', '约 1,300 个', '约 10,000 个'],
    options_en: ['About 10', 'About 100', 'About 1,300', 'About 10,000'],
    answer: 2,
    explain: '木星体积约为地球的 1,300 倍，大约能容纳 1,300 个地球。',
    explain_en: "Jupiter's volume is about 1,300 times Earth's, so roughly 1,300 Earths could fit inside it.",
  },
];

// ============================================================
// 飞行器（先加入旅行者1号，后续可扩展其它著名探测器）
// timeline 中的 x/y/z 为 3D 场景中的轨迹坐标（视觉比例），year 用于飞行中的年份插值
// ============================================================
export const VOYAGER1 = {
  id: 'voyager1',
  name: '旅行者1号',
  en: 'Voyager 1',
  kind: 'spacecraft',
  color: '#ffd166',
  radius: 0.6, // 用于选中高亮圆环的大小
  country: '美国 · NASA',
  country_en: 'USA · NASA',
  launchDate: '1977年9月5日',
  launchDate_en: 'September 5, 1977',
  mass: '825 kg',
  size: '主天线直径 3.7 m · 主体宽约 1.8 m',
  size_en: 'High-gain antenna 3.7 m across · body ~1.8 m wide',
  power: '3 台放射性同位素热电发电机（RTG）',
  power_en: '3 radioisotope thermoelectric generators (RTGs)',
  status: '已进入星际空间（2012-08-25）',
  status_en: 'Entered interstellar space (2012-08-25)',
  desc: '人类飞得最远的探测器。1977 年发射，先后飞掠木星与土星，随后借助土星引力弹弓离开黄道面，如今正穿越星际空间。',
  desc_en: "The farthest human-made object. Launched in 1977, it flew by Jupiter and Saturn, then left the ecliptic plane via a Saturn gravity assist and is now traveling through interstellar space.",
  missionGoals: [
    '飞掠并研究木星及其卫星',
    '飞掠并研究土星、其卫星与光环',
    '探测日球层及其边界',
    '现已进入星际空间，继续采样星际介质',
  ],
  missionGoals_en: [
    'Fly by and study Jupiter and its moons',
    'Fly by and study Saturn, its moons and rings',
    'Probe the heliosphere and its boundary',
    'Now in interstellar space, sampling the interstellar medium',
  ],
  timeline: [
    { date: '1977-09-05', date_en: 'Sep 5, 1977', year: 1977.68, event: '从地球发射升空', event_en: 'Launched from Earth', x: 16, y: 0, z: 0 },
    { date: '1979-03-05', date_en: 'Mar 5, 1979', year: 1979.18, event: '飞掠木星', event_en: 'Jupiter flyby', x: 31, y: 0, z: 14 },
    { date: '1980-11-12', date_en: 'Nov 12, 1980', year: 1980.87, event: '飞掠土星', event_en: 'Saturn flyby', x: 38, y: 0, z: 30 },
    { date: '2012-08-25', date_en: 'Aug 25, 2012', year: 2012.65, event: '进入星际空间', event_en: 'Entered interstellar space', x: 52, y: 8, z: 48 },
    { date: '至今', date_en: 'Present', year: 2025, event: '继续远离太阳飞行', event_en: 'Continuing outward', x: 84, y: 20, z: 70 },
  ],
};

export const VOYAGER2 = {
  id: 'voyager2',
  name: '旅行者2号',
  en: 'Voyager 2',
  kind: 'spacecraft',
  color: '#6fd3ff',
  radius: 0.6,
  country: '美国 · NASA',
  country_en: 'USA · NASA',
  launchDate: '1977年8月20日',
  launchDate_en: 'August 20, 1977',
  mass: '825 kg',
  size: '主天线直径 3.7 m · 主体宽约 1.8 m',
  size_en: 'High-gain antenna 3.7 m across · body ~1.8 m wide',
  power: '3 台放射性同位素热电发电机（RTG）',
  power_en: '3 radioisotope thermoelectric generators (RTGs)',
  status: '已进入星际空间（2018-11-05）',
  status_en: 'Entered interstellar space (2018-11-05)',
  desc: '与旅行者1号同批发射的孪生探测器，是迄今唯一到访过木星、土星、天王星、海王星四颗外行星的探测器，2018 年进入星际空间。',
  desc_en: 'Twin probe of Voyager 1, and the only spacecraft to have visited all four outer planets — Jupiter, Saturn, Uranus and Neptune. It entered interstellar space in 2018.',
  missionGoals: [
    '飞掠并研究木星及其卫星',
    '飞掠并研究土星、其卫星与光环',
    '首次（也是迄今唯一）飞掠天王星',
    '首次（也是迄今唯一）飞掠海王星',
    '现已进入星际空间，继续采样星际介质',
  ],
  missionGoals_en: [
    'Fly by and study Jupiter and its moons',
    'Fly by and study Saturn, its moons and rings',
    'First (and so far only) flyby of Uranus',
    'First (and so far only) flyby of Neptune',
    'Now in interstellar space, sampling the interstellar medium',
  ],
  timeline: [
    { date: '1977-08-20', date_en: 'Aug 20, 1977', year: 1977.64, event: '从地球发射升空', event_en: 'Launched from Earth', x: 16, y: 0, z: 0 },
    { date: '1979-07-09', date_en: 'Jul 9, 1979', year: 1979.52, event: '飞掠木星', event_en: 'Jupiter flyby', x: 31, y: 0, z: 12 },
    { date: '1981-08-26', date_en: 'Aug 26, 1981', year: 1981.65, event: '飞掠土星', event_en: 'Saturn flyby', x: 38, y: 0, z: 24 },
    { date: '1986-01-24', date_en: 'Jan 24, 1986', year: 1986.07, event: '飞掠天王星', event_en: 'Uranus flyby', x: 46, y: 0, z: 34 },
    { date: '1989-08-25', date_en: 'Aug 25, 1989', year: 1989.65, event: '飞掠海王星', event_en: 'Neptune flyby', x: 53, y: 0, z: 42 },
    { date: '2018-11-05', date_en: 'Nov 5, 2018', year: 2018.85, event: '进入星际空间', event_en: 'Entered interstellar space', x: 60, y: 3, z: 52 },
    { date: '至今', date_en: 'Present', year: 2025, event: '继续远离太阳飞行', event_en: 'Continuing outward', x: 80, y: 8, z: 66 },
  ],
};

// ============================================================
// 行星的重要卫星（选中行星时在其周围显示）
// radius/distance 为 3D 视觉参数，speed 为视觉公转角速度
// ============================================================
export const MOONS = {
  mercury: [],
  venus: [],
  earth: [
    { name: '月球', en: 'Moon', radius: 0.16, distance: 2.4, color: '#b8b8b8', speed: 2.0 },
  ],
  mars: [
    { name: '火卫一', en: 'Phobos', radius: 0.09, distance: 1.6, color: '#c9b39a', speed: 3.0 },
    { name: '火卫二', en: 'Deimos', radius: 0.07, distance: 2.4, color: '#b0a89a', speed: 2.0 },
  ],
  jupiter: [
    { name: '木卫一', en: 'Io', radius: 0.16, distance: 3.2, color: '#e0c060', speed: 2.4 },
    { name: '木卫二', en: 'Europa', radius: 0.14, distance: 4.0, color: '#c8d8d8', speed: 1.9 },
    { name: '木卫三', en: 'Ganymede', radius: 0.2, distance: 4.9, color: '#b0a090', speed: 1.5 },
    { name: '木卫四', en: 'Callisto', radius: 0.18, distance: 5.9, color: '#8a7f70', speed: 1.2 },
  ],
  saturn: [
    { name: '土卫六', en: 'Titan', radius: 0.2, distance: 3.4, color: '#e0a860', speed: 1.4 },
    { name: '土卫二', en: 'Enceladus', radius: 0.1, distance: 4.3, color: '#d8e8e8', speed: 1.8 },
    { name: '土卫一', en: 'Mimas', radius: 0.09, distance: 5.0, color: '#c8c0b0', speed: 1.5 },
    { name: '土卫五', en: 'Rhea', radius: 0.13, distance: 5.8, color: '#c0b8b8', speed: 1.2 },
    { name: '土卫八', en: 'Iapetus', radius: 0.12, distance: 6.7, color: '#9a9088', speed: 0.9 },
  ],
  uranus: [
    { name: '天卫五', en: 'Miranda', radius: 0.09, distance: 2.6, color: '#c0c8c8', speed: 2.0 },
    { name: '天卫一', en: 'Ariel', radius: 0.12, distance: 3.3, color: '#b8c8c0', speed: 1.7 },
    { name: '天卫二', en: 'Umbriel', radius: 0.12, distance: 4.0, color: '#8a8a80', speed: 1.4 },
    { name: '天卫三', en: 'Titania', radius: 0.14, distance: 4.8, color: '#c0b0a0', speed: 1.1 },
    { name: '天卫四', en: 'Oberon', radius: 0.14, distance: 5.6, color: '#9a8a78', speed: 0.9 },
  ],
  neptune: [
    { name: '海卫一', en: 'Triton', radius: 0.16, distance: 3.0, color: '#b8d0d8', speed: 1.6 },
    { name: '海卫八', en: 'Proteus', radius: 0.08, distance: 4.0, color: '#90888a', speed: 1.2 },
    { name: '海卫二', en: 'Nereid', radius: 0.08, distance: 5.2, color: '#a8a0a0', speed: 0.8 },
  ],
  pluto: [
    { name: '冥卫一', en: 'Charon', radius: 0.12, distance: 1.4, color: '#b0a898', speed: 2.4 },
    { name: '冥卫二', en: 'Nix', radius: 0.05, distance: 2.0, color: '#a09888', speed: 1.8 },
    { name: '冥卫三', en: 'Hydra', radius: 0.05, distance: 2.6, color: '#a8a090', speed: 1.4 },
  ],
  ceres: [],
  haumea: [
    { name: '妊卫一', en: "Hi'iaka", radius: 0.06, distance: 2.2, color: '#c8c8d0', speed: 1.8 },
    { name: '妊卫二', en: 'Namaka', radius: 0.04, distance: 1.6, color: '#c0c0c8', speed: 2.2 },
  ],
  makemake: [
    { name: '鸟卫一', en: 'MK2', radius: 0.04, distance: 1.8, color: '#b8a898', speed: 2.0 },
  ],
  eris: [
    { name: '阋卫一', en: 'Dysnomia', radius: 0.05, distance: 1.8, color: '#d0d0c8', speed: 2.0 },
  ],
};
